version: '3.4'

services:
  billing:
    image: ${DOCKER_REGISTRY-}billing
    container_name: billing
    build:
      context: .
      dockerfile: src/Services/Billing/Dockerfile
    environment:
     - NServiceBus__Connection__host=rabbitmq
    depends_on:
     - rabbitmq

  hotel:
    image: ${DOCKER_REGISTRY-}hotel
    container_name: hotel
    build:
      context: .
      dockerfile: src/Services/Hotel/Dockerfile
    depends_on:
     - rabbitmq
     - reservation


  reservation:
    image: ${DOCKER_REGISTRY-}reservation
    container_name: reservation
    build:
      context: .
      dockerfile: src/Services/Reservation/Dockerfile
    depends_on:
     - rabbitmq


  webclient:
    image: ${DOCKER_REGISTRY-}webclient
    container_name: webclient
    build:
      context: .
      dockerfile: src/Clients/Client.Mvc/Dockerfile
    depends_on:
     - rabbitmq


  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"